### ISSUE TITLE
Wireless access point mode not working for rpi0

### ISSUE THREAD

**Issue by WilliamBehrens** [nerves-networking/vintage_net_wifi#125]
**Describe the bug**
When adding the access point mode example to my `./config/target.exs` I get no new networks appearing on any device

**Environment**

* Nerves environment: (`mix nerves.env --info`)
==> nerves
==> rcbot
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_br
  Vsn:         1.18.6
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_rpi0
  Vsn:         1.18.4
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, [make_args: ["source", "all", "legal-info"]]}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.8.5
  Type:        toolchain_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_armv6_nerves_linux_gnueabihf
  Vsn:         1.5.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   rpi0
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi0
  toolchain:  /home/will/.nerves/artifacts/nerves_toolchain_armv6_nerves_linux_gnueabihf-linux_x86_64-1.5.0
  system:     /home/will/.nerves/artifacts/nerves_system_rpi0-portable-1.18.4
  app:        .

|nerves_bootstrap| Loadpaths End

**Comment by fhunleth** [comment]
Hi @WilliamBehrens. Do you have access to an iex prompt on your rpi0? For example, can you `ssh` into the device over the USB cable or see any messages over the UART pins. It would be helpful if you could run `VintageNet.info` at the iex prompt. If that's not possible, could you post text that you added to your `target.exs`?
