### ISSUE TITLE
Connection to a Hidden Network

### ISSUE THREAD

**Issue by joserpintuitivo** [nerves-networking/vintage_net_wifi#151]
**Describe the bug**
I can't connect to hidden WiFi networks. Even adding the scan_ssid: 1

**To Reproduce**

**Expected behavior**

**VintageNet Info**

```
2022-12-26 22:46:05.700 [debug] wpa_supplicant(wlan0): Failed to initiate sched scan
2022-12-26 22:46:05.697 [debug] wpa_supplicant: wlan0: Failed to initiate sched scan
2022-12-26 22:46:05.689 [warn] WPASupplicant ignoring {:event, "WPS-AP-AVAILABLE"}
2022-12-26 22:45:57.856 [warn] network not found
```

Output of `VintageNet.info` (please hide any sensitive information like WiFi PSKs)

**Environment**

```
config :vintage_net,
  regulatory_domain: "US",
  config: [
    {"usb0", %{type: VintageNetDirect}},
    {"wlan0",
      %{
        type: VintageNetWiFi,
        vintage_net_wifi: %{
          networks: [
            %{
              key_mgmt: :wpa_psk,
              ssid: "ssid",
              psk: "psk",
              scan_ssid: 1
            }
          ]
        },
        ipv4: %{method: :dhcp},
      }
    },
    {"eth0",
     %{
       type: VintageNetEthernet,
       ipv4: %{method: :dhcp}
     }}
  ]
```

* Nerves environment: (`mix nerves.env --info`)
* Additional information about your host, target hardware or environment that might help

**Additional context**

**Comment by fhunleth** [comment]
Could you let me know what access point you're using, what device this is (assuming Raspberry Pi 4?), and what the hidden WiFi network configuration looks like on the access point?

The reason that I'm asking is that I know of devices that connect fine to hidden WiFi networks. 

Also, could you confirm whether this hidden network uses WPA2 or WPA3?

**Comment by joserpintuitivo** [comment]
I already understood why it does not connect, there was something strange in the previous configuration.
