### ISSUE TITLE
Realtek r8188eu and rpi2 support

### ISSUE THREAD

**Issue by jonlunsford** [nerves-networking/vintage_net_wifi#18]
Hi! I'm struggling to track down the source of my issue using the [TP-LINK TL-WN725N](https://www.tp-link.com/us/support/download/tl-wn725n/) USB wifi dongle with the rpi2 nerves target. I've also tested this with `nerves_network` and have had success.

Basically, I'm not sure if there's an issue with VintageNet or rpi2, the missing `ifup` lib makes me think it might be rpi2, but the failure to initialize the driver interface might be VintageNet. Any guidance on troubleshooting this would be greatly appreciated. Below are the various logs that seem most relevant, let me know if any other info would help.

### Bootup Logs

```
[    3.343259] usb 1-1: New USB device found, idVendor=0424, idProduct=9514, bcdDevice= 2.00
[    3.355632] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.365934] hub 1-1:1.0: USB hub found
[    3.372262] hub 1-1:1.0: 5 ports detected
[    3.693041] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    3.845822] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00, bcdDevice= 2.00
[    3.860439] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.973093] usb 1-1.4: new high-speed USB device number 4 using dwc_otg
[    4.113785] usb 1-1.4: New USB device found, idVendor=0bda, idProduct=8179, bcdDevice= 0.00
[    4.128645] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.139702] usb 1-1.4: Product: 802.11n NIC
[    4.147426] usb 1-1.4: Manufacturer: Realtek
[    4.154995] usb 1-1.4: SerialNumber: 00E04C0001

...

[   11.457493] r8188eu: module is from the staging directory, the quality is unknown, you have been warned.
[   11.537353] usbcore: registered new interface driver r8188eu
[   52.184247] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
```

### VintageNet Info

```Elixir
iex(2)> VintageNet.verify_system
{:error, "Can't find ifup"}
```

```Elixir
iex(3)> VintageNet.info
VintageNet 0.8.0

All interfaces:       ["eth0", "lo", "wlan0"]
Available interfaces: []

Interface eth0
  Type: VintageNetEthernet
  Present: true
  State: :configured (0:02:58)
  Connection: :disconnected (0:02:58)
  Configuration:
    %{ipv4: %{method: :dhcp}, type: VintageNetEthernet}

Interface wlan0
  Type: VintageNetWiFi
  Present: true
  State: :configured (1.5 s)
  Connection: :disconnected (0:02:58)
  Configuration:
    %{
      ipv4: %{method: :dhcp},
      type: VintageNetWiFi,
      vintage_net_wifi: %{
        networks: [
          %{
            key_mgmt: :wpa_psk,
            mode: :infrastructure,
            psk: "....",
            ssid: "....",
            verbose: true
          }
        ]
      }
    }
```
### Application Logs

```Elixir
00:03:19.904 [debug] VintageNet(wlan0): :configured -> internal configure (VintageNetWiFi)

00:03:19.940 [debug] udhcpc(wlan0): udhcpc: started, v1.31.1

00:03:19.943 [info]  wlan0 dhcp deconfig: %{interface: "wlan0"}

00:03:20.012 [debug] udhcpc(wlan0): udhcpc: sending discover

00:03:20.950 [debug] /usr/sbin/wpa_supplicant: Successfully initialized wpa_supplicant

00:03:20.954 [debug] /usr/sbin/wpa_supplicant: nl80211: Driver does not support authentication/association or connect commands

00:03:20.954 [debug] /usr/sbin/wpa_supplicant: nl80211: deinit ifname=wlan0 disabled_11b_rates=0

00:03:20.955 [debug] /usr/sbin/wpa_supplicant: wlan0: Failed to initialize driver interface

00:03:20.957 [error] /usr/sbin/wpa_supplicant: Process exited with status 255

00:03:20.959 [error] GenServer #PID<0.2423.0> terminating
** (stop) :error_exit_status
Last message: {#Port<0.934>, {:exit_status, 255}}
State: %MuonTrap.Daemon.State{cgroup_path: nil, command: "/usr/sbin/wpa_supplicant", log_output: :debug, log_prefix: "/usr/sbin/wpa_supplicant: ", port: #Port<0.934>}
```

### System Info

```
iex(10)> ifconfig
lo: flags=[:up, :loopback, :running]
    inet 127.0.0.1  netmask 255.0.0.0
    inet ::1  netmask ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    hwaddr 00:00:00:00:00:00

eth0: flags=[:up, :broadcast, :running, :multicast]
    hwaddr b8:27:eb:81:de:66

wlan0: flags=[:up, :broadcast, :running, :multicast]
    hwaddr 64:66:b3:25:10:8d
```

**Comment by fhunleth** [comment]
Thanks for posting all of the details. 

The error about `ifup` missing is old and I should fix that. 

What version of `nerves_system_rpi2` and `nerves_system_br` are you using?

I'm wondering about this line:
```
00:03:20.954 [debug] /usr/sbin/wpa_supplicant: nl80211: Driver does not support authentication/association or connect commands
```
I'm not sure that I've seen that before and it reads strangely to me especially if `nerves_network` worked for you.

**Comment by jonlunsford** [comment]
Ah, good to know about `ifup`. Yeah, it _really_ seems like the drivers should be ok. Was able to get `nerves_network` working in this same project, along side `VintageNet`, but after cleaning deps I get the deprecation warnings to remove it. Here's the `nerves.info` output:

```bash
  Pkg:         nerves_system_br
  Vsn:         1.11.4
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_rpi2
  Vsn:         1.11.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.3.2
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.7.2
  Type:        toolchain_platform
  BuildRunner: {nil, []}


  Nerves:           1.6.3
  Nerves Bootstrap: 1.8.0
  Elixir:           1.10.2
```

**Comment by fhunleth** [comment]
Thanks.

And yes, `vintage_net` and `nerves_network` don't play nice with each other so that's the reason for the warnings. It's definitely some clue that `nerves_network` works, though. The only thing that I can think of is that we got more sophisticated with `vintage_net` with WiFi and maybe we're exercising something that's not as well-supported on the r8188eu. 

When I get a chance, I'll dig through that nl80211 warning to see what it really means. 

@ConnorRigby Do you have an r8188eu adapter?

**Comment by ConnorRigby** [comment]
Just picked one up, should have time to investigate tomorrow! I think i've actually seen this error before and if i remember correctly, it's an issue with the driver/firmware combination, meaning one of them may be out of sync with the other.

**Comment by jonlunsford** [comment]
Ah! That seems probable. Fwiw, this exact dongle is their v1 hardware I believe. Noted [here](https://www.tp-link.com/us/support/faq/46/) on how to find the hardware version via engraved characters. The FCC ID on this device:

`TE7WN725N`

**Comment by ConnorRigby** [comment]
@jonlunsford i just tried my r8188eu adapter out on rpi3 (i don't have an rpi2) and it worked fine for me. I'm still looking into other things for you.

**Comment by jonlunsford** [comment]
@ConnorRigby thanks for the update! Hmm, yeah, had a suspicion it may be related to rpi2, but I'm not clear what the relevant differences between the two builds are. I was also attempting to understand the differences between `nerves_network` and `VintageNet` as well, I still don't understand why one works and one does not on rpi2.

**Comment by fhunleth** [comment]
@jonlunsford I'm going to close this, since I'm not sure what more we can do to help. We have a hard time supporting many WiFi adapters since there's a lot of variation in driver quality and whether we're even using up-to-date firmware blobs. We're better equipped to debug issues with built-in WiFi modules on the RPi 0W, RPi 3 B+, A+ and RPi 4. If you're still having problems, I'd recommend trying to switch to one of those. (I'd personally pick the 3 B+ if you're generally happy with the RPi 2 other than this).

**Comment by jonlunsford** [comment]
Thanks @fhunleth, yeah, I may end up switching hardware then. I was being stubborn and trying use old PIs I had laying around :) Thanks for taking the time to investigate! I'll fallow up if anything progresses as well.
