### ISSUE TITLE
WPS_PBC support

### ISSUE THREAD

**Issue by labno** [nerves-networking/vintage_net_wifi#49]
Hey there!

I'm unsure about the state of WPS support in this project.
The flag "wps" gets reported when scanning for APs, but there does not seem to be a documented way to connect to a wifi via WPS (button mode).
You can make it work with `WPASupplicantLL`, as such: 
```
{:ok, ws} = VintageNetWiFi.WPASupplicantLL.start_link(path: "/tmp/vintage_net/wpa_supplicant/wlan0", notification_pid: self())

VintageNetWiFi.WPASupplicantLL.control_request(ws, "WPS_PBC")
```
This usually connects, given the control file `wlan0` does already exist and there is no active config for the interface.
However, since this bypasses VintageNet completely, `VintageNet.info` shows nothing afterwards and nothing is persisted.

Am I missing something here? Is there a more straight-forward way to connect via WPS?
Would it even be possible to persist such a wifi configuration in the way other wifi configs are written to disk?

Thanks in advance!

**Comment by fhunleth** [comment]
I have not used WPS in forever and I don't have any access points that support it. Could you remind me how it works? Is it?

1. Put device in WPS mode
2. Press button on AP
3. Device connects to AP

It sounds to me like a exposing some messages to and from the `wpa_supplicant` and adding a helper function to automate it and save the result would do it.

**Comment by labno** [comment]
Yes, thats's exactly how it works.
True, exposing the `WPS_PBC` message in a function would do it. The tricky part is "save the results".  `VintageNet` directly saves the config given to it via e.g. `VinageNet.configure`, if I'm not mistaken. But in the WPS case, there is no such thing, no wifi key is given explicitly, so nothing can be persisted. That means I can connect via WPS with the method given above, but would have to do so after each device reboot.

I'm not too familiar with the inner workings of `wpa_supplicant`, but it has to keep the wifi key it got via WPS somewhere, right? Maybe it could be extracted and used to build and persist a regular `VintageNetWiFi` config map.
Any ideas how one could get a hold of the wifi data supplied via WPS after a connection is established?

Thanks!

**Comment by fhunleth** [comment]
I think we need to follow this document: http://w1.fi/cgit/hostap/tree/wpa_supplicant/README-WPS

What I'd do is get a Linux machine, disable network manager and manually run the wpa_supplicant to connect to the WPS access point. If you get a script of what things look like with `wpa_cli` and the interactions, everything gets to be more clear. `wpa_cli` messages are pretty low level and correspond to `VintageNetWiFi` fairly closely.

Anyway, here's my skim:

1. Set `wps_cred_processing=1` in the conf file to disable internal credential processing. I think we need to process credentials to save them for next time.
2. Capture WPS-CRED-RECEIVED events and save them to a VintageNet property. That will let a program wait for them. for experimentation, just getting the WPS-CRED-RECEIVED message in the `wpa_cli` on Linux will be interesting.
3. Send WPS_PBC - via `VintageNetWiFi.ioctl` like how scanning for networks is done
4. Wait to receive the credentials
5. Create a VintageNet config from the credentials. It looks like they're decoded here: http://w1.fi/cgit/hostap/tree/wpa_supplicant/wps_supplicant.c#n366. I'm having trouble reading the code quickly and wondering if the WiFi spec is easier to read. It looks like all of the important stuff is there, though.

For VintageNetWiFi, I think that the only changes are to expose the WPS credentials, support WPS_PBC and then have a helper function to convert credentials to WiFi configs. The rest of the process of updating configs can be something the user of VintageNetWiFi does or we could add a `VintageNetWiFi.quick_wps` function to automate the process  like the other quick functions.

**Comment by labno** [comment]
Awesome, thank you for your detailed pointers!
I'm getting the credential data blobs. Once I figure out how they are encoded, I'll try an implementation some time next week.
Are you interested in a PR?
Thanks again!

**Comment by fhunleth** [comment]
Yes, this seems like a good feature to add. Thanks for figuring this out.

**Comment by labno** [comment]
I finally got around to this.
The credentials received via WPS are a hex dump consisting of ssid, psk and quite a few control chars I couldn't really make sense of. So I made the pragmatic choice of just extracting whatever looks like an ascii- string and throwing the rest away.
It works...but let me know if it's too hacky for you.
