### ISSUE TITLE
Static IP not working?

### ISSUE THREAD

**Issue by mnishiguchi** [nerves-networking/vintage_net_wifi#60]
## Background

I attempted to configure static IP addresses for my three raspberry Pis (all model Zero W) using `VintageNetWiFi`.
All I did is basically switch from DHCP to a minimal static IP setting. I see a few strange phenomena and the static IP is not working as expected.

Here is the setting I applied to all the device:

```diff
  config :vintage_net,
    regulatory_domain: "US",
    config: [
      {"usb0", %{type: VintageNetDirect}},
      {"eth0",
      %{
        type: VintageNetEthernet,
        ipv4: %{method: :dhcp}
      }},
      {"wlan0",
      %{
        type: VintageNetWiFi,
        vintage_net_wifi: %{
          networks: [
            %{
              key_mgmt: :wpa_psk,
              ssid: System.get_env("WIFI_SSID"),
              psk: System.get_env("WIFI_PSK")
            }
          ]
        },
-       ipv4: %{method: :dhcp}
+       ipv4: %{
+        method: :static,
+        address: "10.0.0.201",
+        prefix_length: 24
+      }
      }}
    ]
```

## Problems

I see strange behavior in two patterns.
I tweaked the setting by adding optional values such `gateway` and `netmask` but results were the same.
I wonder if these are my setting specific or something is missing.

**Device A**

This one device is so stubborn that its IP is always `10.0.0.204` no matter what IP I specify in its config. This happens to be Nerves Livebook but I don't know if it is relevant.

- IP in config: `10.0.0.201`
- ❌ get assigned the IP I specified
- ✅ `ssh 10.0.0.204` (different IP though ¯\_(ツ)_/¯)
- ✅ `ping "https://nerves-project.org"`

**Device B**

My other two devices have correct IP addresses but it cannot access the Internet.

- IP in config: `10.0.0.202`
- ✅ get assigned the IP I specified
- ✅ `ssh 10.0.0.202`
- ❌ `ping "https://nerves-project.org"`

## My local network

![Screen Shot 2021-06-21 at 5 27 17 PM](https://user-images.githubusercontent.com/7563926/122844049-d2671900-d2ce-11eb-8df9-11ef88f865be.png)

## Related links

- [VintageNet Cookbook](https://hexdocs.pm/vintage_net/cookbook.html)
- [VintageNet WiFi unit test](https://github.com/nerves-networking/vintage_net_wifi/blob/0209a0a6db77c2dafaabafcca3685a962cca94d1/test/vintage_net_wifi_test.exs#L1754-L1767)
- [VintageNet WiFi documentations](https://hexdocs.pm/vintage_net_wifi/readme.html)

**Comment by fhunleth** [comment]
This part of the configuration specifically disables Internet access (the default gateway isn't set), so I think what you're seeing is the right thing (i.e. right IP, no internet).

```
ipv4: %{
        method: :static,
        address: "10.0.0.201",
        prefix_length: 24
      }
```

Could you run `VintageNet.info` to check the runtime configuration? If you have a saved config, VintageNet uses that. The application config only specifies defaults. If you want to remove the saved configuration and go back to the default, run `VintageNet.reset_to_defaults("wlan0")`.

**Comment by mnishiguchi** [comment]
Ah I see. My old config seems still alive as I run `VintageNet.info` on Device A.

```
Interface wlan0
  Type: VintageNetWiFi
  Present: true
  State: :configured (11.6 s)
  Connection: :internet (8.1 s)
  Addresses: ...
  Configuration:
    %{
      ipv4: %{method: :dhcp},
      type: VintageNetWiFi,
      vintage_net_wifi: %{
        networks: [
          %{
            key_mgmt: :wpa_psk,
            mode: :infrastructure,
            psk: "....",
            ssid: "..."
          }
        ]
      }
    }
```

**Comment by fhunleth** [comment]
Could you changing your name server to 1.1.1.1? You can access the internet, but DNS isn't working.

**Comment by mnishiguchi** [comment]
Thanks Frank. `name_servers: [“1.1.1.1”]` worked. Now I get a response from nerves-project.org.

```elixir
       ipv4: %{
         method: :static,
         address: "10.0.0.202",
         prefix_length: 24,
         gateway: "10.0.0.1",
         name_servers: ["1.1.1.1"]
       }
```

**Comment by mnishiguchi** [comment]
After setting up the above mentioned, I cannot access Github including this page on Chrome (my main browser), I wonder if it is related to my Nerves network settings 🤔

**Comment by mnishiguchi** [comment]
Oh after a while, my Chrome works as normal 🤷
