### ISSUE TITLE
[wpa_supplicant] Unknown flag: "WPA2-EAP-CCMP+TKIP" and "WPA-EAP-CCMP"

### ISSUE THREAD

**Issue by dognotdog** [nerves-networking/vintage_net_wifi#61]
`[warn] [wpa_supplicant] Unknown flag: "WPA2-EAP-CCMP+TKIP"`
keeps coming up on an rpi zero w when scanning, is this simply because `WPA2-EAP-CCMP+TKIP` is not in the list of the flag parser? `WPA-EAP-CCMP+TKIP` seems to exist, and there seems to be no other reference to that flag except for the typespec, so it looks like this is just a simple omission.

EDIT: now also seen "WPA-EAP-CCMP" pop-up as an unnown flag.

**Comment by fhunleth** [comment]
Yes, that's an omission. Could you send a PR that adds both of those flags?

p.s. Connor and I are finding out that there's way more variety in these flags than it initially looked and we'll have to find a better way of dealing with this. However, in the mean time, feel free to add any flag that you see. I'll accept all of the PRs.

**Comment by dognotdog** [comment]
The flag format for these seems to be `<protocol>-<authentication>-<encryption>`, but I haven't been able to find a source for this.

**Comment by fhunleth** [comment]
Thanks for sending the PR.

Yes, I believe that's the format. I found the source once and almost made the code more generic. I think it needs a little more thought, though. The use case for this is to figure out what kind of network you need to setup. It would be easier if `VintageNetWiFi` just told you what you needed to connect to the network. I'm waiting on a WiFi config wizard that someone writes that does this classification for more than just WPA2 and EAP and then pulling it in as a utility for everyone. Or at least that's the current plan.
